
        // Synchronized Master Restaurant Dataset List matching your main app configuration
   const restaurants=[
  
  {
    "image": "https://b.zmtcdn.com/data/pictures/3/22295613/aade5a7026490f1cdc60f7f5dc094f78_featured_v2.jpg?output-format=webp",
    "names": "Babylon Brewery & Club",
    "rating": "3.8",
    "foodtypes": "North Indian",
    "location": "Varanasi",
    "price_for-two": 200,
    "distance": "24 min",
    "offers": "No Offer",
    "offer-status":false,
    "alcohol": false,
    "res-open_time": 17,
    "res-close_time": 5,
    "pet_friendly": false,
    "outdoor_seating": true
  },{
    
    "image": "https://b.zmtcdn.com/data/pictures/7/21066027/cefeafeafbafba5a5fff543a4d6cd86c_featured_v2.jpg",
    "names": "The Food Factory",
    "rating": "3.9",
    "foodtypes": "Fast Food, Street Food",
    "location": "Thiruvananthapuram",
    "price_for-two": 150,
    "distance": "39 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 15,
    "res-close_time": 3,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/20983729/7845f3ec74a7d30ed8e6c6463ba6c489_featured_v2.jpg",
    "names": "Hotel Karthikeya",
    "rating": "3.8",
    "foodtypes": "Fast Food",
    "location": "Bhopal",
    "price_for-two": 2500,
    "distance": "32 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": true,
    "res-open_time": 3,
    "res-close_time": 15,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/dish_photos/9fe/687b7d18ae02582d2a6c3746958f09fe.jpg",
    "names": "Domino's Pizza",
    "rating": "4.8",
    "foodtypes": "Pizza, Pasta",
    "location": "Indore",
    "price_for-two": 150,
    "distance": "44 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 14,
    "res-close_time": 2,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/21835339/a04b7a7438b9d0844f711a0ac2c79c62_featured_v2.jpg?output-format=webp",
    "names": "Tandoori Nights",
    "rating": "4.9",
    "foodtypes": "South Indian",
    "location": "Ameerpet",
    "price_for-two": 200,
    "distance": "26 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 4,
    "res-close_time": 16,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/3/18740463/06984575c51d8b899af4c81c1d0f3bbf_o2_featured_v2.jpg",
    "names": "Golden Spoon",
    "rating": "3.7",
    "foodtypes": "Biryani",
    "location": "Patna",
    "price_for-two": 200,
    "distance": "18 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 8,
    "res-close_time": 20,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/5/18740985/6e96bfb00b9dd20195385f866d3e0e10_featured_v2.jpg",
    "names": "Red Chilli Kitchen",
    "rating": "4.7",
    "foodtypes": "Fast Food",
    "location": "Kochi",
    "price_for-two": 2500,
    "distance": "43 min",
    "offer-status":true,
    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 23,
    "res-close_time": 11,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/22044921/4c9622fe6ba60a5579ca2ef7e1c561c6_o2_featured_v2.jpg?output-format=webp",
    "names": "Moonlight Dining",
    "rating": "3.7",
    "foodtypes": "Hyderabadi",
    "location": "Banjara Hills",
    "price_for-two": 500,
    "distance": "32 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 3,
    "res-close_time": 15,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/21977795/cdf091bb342fc06f2f5f17d25a00bd94_featured_v2.jpg",
    "names": "Cafe Aroma",
    "rating": "4.1",
    "foodtypes": "North Indian, Biryani",
    "location": "Nellore",
    "price_for-two": 150,
    "distance": "19 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": true,
    "res-open_time": 6,
    "res-close_time": 18,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/6/22179326/8cdbaf4aa2ae34e124b928bb14ccc35e_featured_v2.jpg",
    "names": "Ajmeer Hotel",
    "rating": "3.8",
    "foodtypes": "BBQ, Kebabs",
    "location": "Nagpur",
    "price_for-two": 500,
    "distance": "44 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 8,
    "res-close_time": 20,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/8/20540418/627a80797b35d84fb979966ab25e93a8_featured_v2.jpg",
    "names": "Ajmeer Hotel",
    "rating": "4.6",
    "foodtypes": "Italian, Mexican",
    "location": "Malakpet",
    "price_for-two": 2500,
    "distance": "25 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 6,
    "res-close_time": 18,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/21962609/8fb3c84f6912d7fb7e8860c76d58abd5_featured_v2.jpg",
    "names": "The Rustic Table",
    "rating": "3.8",
    "foodtypes": "Ice Cream, Healthy Food",
    "location": "Indore",
    "price_for-two": 2500,
    "distance": "21 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": true,
    "res-open_time": 3,
    "res-close_time": 15,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/21977795/cdf091bb342fc06f2f5f17d25a00bd94_featured_v2.jpg",
    "names": "Urban Tandoor",
    "rating": "4.0",
    "foodtypes": "Arabian, Seafood",
    "location": "Hyderabad",
    "price_for-two": 2500,
    "distance": "31 min",
    "offer-status":true,
    "offers": "Flat 20% OFF",
    "alcohol": true,
    "res-open_time": 2,
    "res-close_time": 14,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/dish_photos/c99/4e6a434f974f55af107245eaf5444c99.jpg",
    "names": "Dessert's House",
    "rating": "4.3",
    "foodtypes": "Desserts, Bakery",
    "location": "Hubballi",
    "price_for-two": 200,
    "distance": "24 min",
    "offer-status":true,
    "offers": "₹151 OFF",
    "alcohol": true,
    "res-open_time": 23,
    "res-close_time": 11,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/5/18740985/6e96bfb00b9dd20195385f866d3e0e10_featured_v2.jpg",
    "names": "The Rustic Table",
    "rating": "4.8",
    "foodtypes": "South Indian",
    "location": "Mehdipatnam",
    "price_for-two": 200,
    "distance": "33 min",
    "offers": "No Offer",
    "offer-status":false,
    "alcohol": false,
    "res-open_time": 20,
    "res-close_time": 8,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/0/20809030/cdf11e58a3ef5489585c12378b9fe4ad_featured_v2.jpg",
    "names": "Skyline Diner",
    "rating": "4.4",
    "foodtypes": "Fast Food, Street Food",
    "location": "Malakpet",
    "price_for-two": 500,
    "distance": "30 min",
    "offers": "Flat 30% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 1,
    "res-close_time": 13,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/21984181/15c9c46229a356c77745053b065e5af4_featured_v2.jpg",
    "names": "Ajmeer Maharaj Hotel",
    "rating": "4.6",
    "foodtypes": "Chinese, Mughlai",
    "location": "Mehdipatnam",
    "price_for-two": 200,
    "distance": "31 min",
    "offers": "₹151 OFF",
    "alcohol": false,
    "offer-status":true,
    "res-open_time": 6,
    "res-close_time": 18,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/21577575/7f35c43ff091a48d6c1acd159af3efb8_featured_v2.jpg",
    "names": "Harvest Kitchen",
    "rating": "5.0",
    "foodtypes": "Mughlai",
    "location": "Chennai",
    "price_for-two": 150,
    "distance": "16 min",
    "offers": "Flat 50% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 7,
    "res-close_time": 19,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/7/20647727/d7151701bcdcbd6e8550e2b7eb5d110a_featured_v2.jpg",
    "names": "Cafe Aroma",
    "rating": "4.3",
    "foodtypes": "North Indian, Biryani",
    "location": "Ameerpet",
    "price_for-two": 200,
    "distance": "42 min",
    "offers": "₹121 OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 22,
    "res-close_time": 10,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/20892247/3734149d077a7cc8e141f34f6acbb30e_featured_v2.jpg",
    "names": "Blue Lagoon Restaurant",
    "rating": "4.7",
    "foodtypes": "Mughlai",
    "location": "Delhi",
    "price_for-two": 2500,
    "distance": "18 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": true,
    "res-open_time": 19,
    "res-close_time": 7,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/21577575/7f35c43ff091a48d6c1acd159af3efb8_featured_v2.jpg",
    "names": "The Rustic Table",
    "rating": "4.0",
    "foodtypes": "Continental, Turkish, Indian",
    "location": "Bhopal",
    "price_for-two": 500,
    "distance": "32 min",
    "offers": "Flat 50% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 8,
    "res-close_time": 20,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/21503991/cb680d632e34fb3a153ec501c3c6c0ee_featured_v2.jpg",
    "names": "Tandoori Nights",
    "rating": "3.8",
    "foodtypes": "Chinese",
    "location": "Pune",
    "price_for-two": 500,
    "distance": "44 min",
    "offers": "No Offer",
    "offer-status":false,
    "alcohol": false,
    "res-open_time": 20,
    "res-close_time": 8,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/21003129/04112c8943533daa6d2465256856c7da_o2_featured_v2.jpg",
    "names": "Hotel Baaratheon",
    "rating": "3.9",
    "foodtypes": "Andhra, Telangana",
    "location": "Vijayawada",
    "price_for-two": 200,
    "distance": "30 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 14,
    "res-close_time": 2,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/20983729/7845f3ec74a7d30ed8e6c6463ba6c489_featured_v2.jpg",
    "names": "Street Feast",
    "rating": "3.5",
    "foodtypes": "Hyderabadi",
    "location": "Bengaluru",
    "price_for-two": 150,
    "distance": "44 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": true,
    "res-open_time": 10,
    "res-close_time": 22,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/0/20809030/cdf11e58a3ef5489585c12378b9fe4ad_featured_v2.jpg",
    "names": "Tandoori Nights",
    "rating": "3.9",
    "foodtypes": "Fast Food, Street Food",
    "location": "Mehdipatnam",
    "price_for-two": 200,
    "distance": "38 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 21,
    "res-close_time": 9,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/18382171/6d52ac47b9a51db0dc96f19c8f820a41_featured_v2.jpg",
    "names": "The Curry Bowl",
    "rating": "3.9",
    "foodtypes": "Continental, Turkish, Indian",
    "location": "Mehdipatnam",
    "price_for-two": 500,
    "distance": "15 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 10,
    "res-close_time": 22,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/20647719/d71443c786caaf06694b50a699a8a5d6_featured_v2.jpg",
    "names": "Ocean Pearl",
    "rating": "4.2",
    "foodtypes": "Ice Cream, Healthy Food",
    "location": "Hyderabad",
    "price_for-two": 2500,
    "distance": "41 min",
    "offers": "₹101 OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 10,
    "res-close_time": 22,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/21503991/cb680d632e34fb3a153ec501c3c6c0ee_featured_v2.jpg",
    "names": "Mughal Darbar",
    "rating": "4.3",
    "foodtypes": "Ice Cream, Healthy Food",
    "location": "Ahmedabad",
    "price_for-two": 150,
    "distance": "23 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": true,
    "res-open_time": 14,
    "res-close_time": 2,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/19461655/9079e1636a24751898dba9414c4440ca_featured_v2.jpg",
    "names": "Hotel Baaratheon",
    "rating": "4.9",
    "foodtypes": "North Indian, Mughlai",
    "location": "Thiruvananthapuram",
    "price_for-two": 150,
    "distance": "31 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": true,
    "res-open_time": 16,
    "res-close_time": 4,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/8/21819518/fb1aea765438bf1992bf367a05cf9fb8_featured_v2.jpg",
    "names": "Cafe Aroma",
    "rating": "4.7",
    "foodtypes": "Continental",
    "location": "Malakpet",
    "price_for-two": 500,
    "distance": "31 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 4,
    "res-close_time": 16,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/6/22032946/e91a99e72302d7e0813b78e4f0978d3a_featured_v2.jpg",
    "names": "Citrus Kitchen",
    "rating": "4.5",
    "foodtypes": "Fast Food, Street Food",
    "location": "Jaipur",
    "price_for-two": 200,
    "distance": "31 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": true,
    "res-open_time": 8,
    "res-close_time": 20,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/4/19630684/9d4bb7ce81fba63e5e2e02449fcc0934_featured_v2.jpg",
    "names": "Dragon Fruits",
    "rating": "4.3",
    "foodtypes": "Biryani",
    "location": "Vijayawada",
    "price_for-two": 2500,
    "distance": "23 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 9,
    "res-close_time": 21,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/6/22179326/8cdbaf4aa2ae34e124b928bb14ccc35e_featured_v2.jpg",
    "names": "Peppercorn Restaurant",
    "rating": "4.3",
    "foodtypes": "Street Food,Pizza",
    "location": "Ameerpet",
    "price_for-two": 500,
    "distance": "21 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": true,
    "res-open_time": 4,
    "res-close_time": 16,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/21066027/cefeafeafbafba5a5fff543a4d6cd86c_featured_v2.jpg",
    "names": "Bamboo Garden",
    "rating": "3.7",
    "foodtypes": "BBQ, Kebabs",
    "location": "Pune",
    "price_for-two": 150,
    "distance": "44 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 10,
    "res-close_time": 22,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/21003129/04112c8943533daa6d2465256856c7da_o2_featured_v2.jpg",
    "names": "The Rustic Table",
    "rating": "3.9",
    "foodtypes": "South Indian",
    "location": "Charminar",
    "price_for-two": 200,
    "distance": "27 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 10,
    "res-close_time": 22,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/3/18712173/b78e2f4181db1df2fdd5c5fccb80288f_featured_v2.jpg",
    "names": "Fusion Bistro",
    "rating": "3.8",
    "foodtypes": "Pizza, Pasta",
    "location": "Santoshnagar & Saidabad",
    "price_for-two": 2500,
    "distance": "25 min",
    "offers": "₹101 OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 16,
    "res-close_time": 4,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/2/20496432/2a6b302fcf1695f1e84c02a6ea361f70_featured_v2.jpg",
    "names": "Hotel Baaratheon",
    "rating": "3.9",
    "foodtypes": "Street Food,Pizza",
    "location": "Kochi",
    "price_for-two": 200,
    "distance": "34 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 0,
    "res-close_time": 12,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/0/20388020/0fc6b220297879e1f4080d765b7965f0_featured_v2.jpg",
    "names": "La Pino'z Pizza",
    "rating": "4.1",
    "foodtypes": "Italian, Mexican",
    "location": "Surat",
    "price_for-two": 150,
    "distance": "38 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 20,
    "res-close_time": 8,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/2/18741322/e25bd676805b4a01e37b7e13011a18b3_featured_v2.jpg",
    "names": "Flavors of India",
    "rating": "4.8",
    "foodtypes": "Chinese, Mughlai",
    "location": "Tirupati",
    "price_for-two": 200,
    "distance": "19 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": true,
    "res-open_time": 6,
    "res-close_time": 18,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/19178659/66b3ed1e88d64f9234d6bfd91176a22a_featured_v2.jpg",
    "names": "Grand Hotel",
    "rating": "4.6",
    "foodtypes": "Andhra, Telangana",
    "location": "Himayath Nagar",
    "price_for-two": 500,
    "distance": "34 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": true,
    "res-open_time": 5,
    "res-close_time": 17,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/21984181/15c9c46229a356c77745053b065e5af4_featured_v2.jpg",
    "names": "The Hungry Fork",
    "rating": "3.6",
    "foodtypes": "North Indian, Mughlai",
    "location": "Amritsar",
    "price_for-two": 2500,
    "distance": "31 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 8,
    "res-close_time": 20,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/0/20388020/0fc6b220297879e1f4080d765b7965f0_featured_v2.jpg",
    "names": "The Curry Bowl",
    "rating": "3.6",
    "foodtypes": "Biryani",
    "location": "Vijayawada",
    "price_for-two": 500,
    "distance": "36 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 20,
    "res-close_time": 8,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/21977795/cdf091bb342fc06f2f5f17d25a00bd94_featured_v2.jpg",
    "names": "Flavors of India",
    "rating": "4.4",
    "foodtypes": "Maharashtrian,Punjabi",
    "location": "Banjara Hills",
    "price_for-two": 500,
    "distance": "40 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 9,
    "res-close_time": 21,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/8/21819518/fb1aea765438bf1992bf367a05cf9fb8_featured_v2.jpg",
    "names": "Ocean Pearl",
    "rating": "3.8",
    "foodtypes": "Arabian, Seafood",
    "location": "Chandigarh",
    "price_for-two": 500,
    "distance": "38 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 21,
    "res-close_time": 9,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/3/18880623/224fa5447ce4c8e408ae5665ca2120c6_featured_v2.jpg",
    "names": "The Rustic Table",
    "rating": "4.5",
    "foodtypes": "North Indian, Mughlai",
    "location": "Mumbai",
    "price_for-two": 200,
    "distance": "43 min",
    "offers": "₹101 OFF",
    "offer-status":true,
    "alcohol": true,
    "res-open_time": 22,
    "res-close_time": 10,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/6/21760176/cf1fd421e2afba4e513b82ec4fd40aaf_o2_featured_v2.jpg",
    "names": "La Pino'z Pizza",
    "rating": "4.9",
    "foodtypes": "Continental, Turkish, Indian",
    "location": "Himayath Nagar",
    "price_for-two": 150,
    "distance": "24 min",
    "offers": "Flat 50% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 16,
    "res-close_time": 4,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/5/18740985/6e96bfb00b9dd20195385f866d3e0e10_featured_v2.jpg",
    "names": "Maharaj Hotel",
    "rating": "4.5",
    "foodtypes": "Continental",
    "location": "Kanpur",
    "price_for-two": 500,
    "distance": "28 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": true,
    "res-open_time": 5,
    "res-close_time": 17,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/18382171/6d52ac47b9a51db0dc96f19c8f820a41_featured_v2.jpg",
    "names": "Red Chilli Kitchen",
    "rating": "3.8",
    "foodtypes": "BBQ, Kebabs",
    "location": "Lucknow",
    "price_for-two": 2500,
    "distance": "15 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 8,
    "res-close_time": 20,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/2/18741322/e25bd676805b4a01e37b7e13011a18b3_featured_v2.jpg",
    "names": "Bamboo Garden",
    "rating": "4.2",
    "foodtypes": "Burger",
    "location": "Vijayawada",
    "price_for-two": 150,
    "distance": "37 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": true,
    "res-open_time": 4,
    "res-close_time": 16,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/22044921/4c9622fe6ba60a5579ca2ef7e1c561c6_o2_featured_v2.jpg?output-format=webp",
    "names": "Hotel Baaratheon",
    "rating": "3.9",
    "foodtypes": "Fast Food, Street Food",
    "location": "Mysuru",
    "price_for-two": 200,
    "distance": "43 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 12,
    "res-close_time": 0,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/20521297/03ba87b3729f88d9fdfd77b50ce6452b_o2_featured_v2.jpg",
    "names": "Ajmeer Maharaj Hotel",
    "rating": "4.9",
    "foodtypes": "Arabian, Seafood",
    "location": "Kolkata",
    "price_for-two": 150,
    "distance": "15 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 5,
    "res-close_time": 17,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/8/21819518/fb1aea765438bf1992bf367a05cf9fb8_featured_v2.jpg",
    "names": "Street Feast",
    "rating": "3.6",
    "foodtypes": "North Indian, Biryani",
    "location": "Patna",
    "price_for-two": 200,
    "distance": "36 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 19,
    "res-close_time": 7,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/3/18741033/6f5be30b64957051d51709a44f3820cf_featured_v2.jpg",
    "names": "Velvet Plate",
    "rating": "4.5",
    "foodtypes": "Andhra, Telangana",
    "location": "Himayath Nagar",
    "price_for-two": 200,
    "distance": "23 min",
    "offers": "Flat 10% OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 5,
    "res-close_time": 17,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/4/21157364/a8774abd8db0886901eb25f207a7f504_o2_featured_v2.jpg",
    "names": "Ocean Pearl",
    "rating": "3.6",
    "foodtypes": "Arabian, Seafood",
    "location": "Amritsar",
    "price_for-two": 150,
    "distance": "39 min",
    "offers": "₹101 OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 16,
    "res-close_time": 4,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/2/20282542/5bce73f21a3f49cf45ae4ac5712c340a_featured_v2.jpg",
    "names": "The Rustic Table",
    "rating": "4.9",
    "foodtypes": "Chinese",
    "location": "Varanasi",
    "price_for-two": 500,
    "distance": "44 min",
    "offers": "No Offer",
    "offer-status":false,
    "alcohol": false,
    "res-open_time": 2,
    "res-close_time": 14,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/21003129/04112c8943533daa6d2465256856c7da_o2_featured_v2.jpg",
    "names": "Mirell Restaurant",
    "rating": "4.3",
    "foodtypes": "Desserts, Bakery",
    "location": "Darulshifa",
    "price_for-two": 200,
    "distance": "25 min",
    "offers": "₹101 OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 2,
    "res-close_time": 14,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/20892247/3734149d077a7cc8e141f34f6acbb30e_featured_v2.jpg",
    "names": "Ajmeer Maharaj Hotel",
    "rating": "4.1",
    "foodtypes": "Thai, Japanese",
    "location": "Mangaluru",
    "price_for-two": 150,
    "distance": "37 min",
    "offers": "₹101 OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 13,
    "res-close_time": 1,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/0/20388020/0fc6b220297879e1f4080d765b7965f0_featured_v2.jpg",
    "names": "Peppercorn Restaurant",
    "rating": "4.5",
    "foodtypes": "Continental, Turkish, Indian",
    "location": "Amritsar",
    "price_for-two": 200,
    "distance": "42 min",
    "offer-status":true,

    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 20,
    "res-close_time": 8,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/0/18877520/5a571393766c277b916d70a453b85bac_featured_v2.jpg",
    "names": "Taste Junction",
    "rating": "4.4",
    "foodtypes": "BBQ, Kebabs",
    "location": "Chennai",
    "price_for-two": 150,
    "distance": "38 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 6,
    "res-close_time": 18,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/21977795/cdf091bb342fc06f2f5f17d25a00bd94_featured_v2.jpg",
    "names": "Green Leaf Cafe",
    "rating": "3.9",
    "foodtypes": "North Indian",
    "location": "Nellore",
    "price_for-two": 2500,
    "distance": "40 min",
    "offer-status":true,
    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 18,
    "res-close_time": 6,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/18382171/6d52ac47b9a51db0dc96f19c8f820a41_featured_v2.jpg",
    "names": "Moonlight Dining",
    "rating": "4.9",
    "foodtypes": "Pizza, Pasta",
    "location": "Charminar",
    "price_for-two": 2500,
    "distance": "29 min",
    "offer-status":true,

    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 16,
    "res-close_time": 4,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/21066027/cefeafeafbafba5a5fff543a4d6cd86c_featured_v2.jpg",
    "names": "Taste Junction",
    "rating": "4.4",
    "foodtypes": "Pizza, Pasta",
    "location": "Bhopal",
    "price_for-two": 2500,
    "distance": "15 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 17,
    "res-close_time": 5,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/21066027/cefeafeafbafba5a5fff543a4d6cd86c_featured_v2.jpg",
    "names": "Royal Biryani House",
    "rating": "4.2",
    "foodtypes": "Thai, Japanese",
    "location": "Amritsar",
    "price_for-two": 200,
    "distance": "23 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 8,
    "res-close_time": 20,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/21962609/8fb3c84f6912d7fb7e8860c76d58abd5_featured_v2.jpg",
    "names": "Fire & Grill",
    "rating": "4.7",
    "foodtypes": "Street Food,Pizza",
    "location": "Surat",
    "price_for-two": 500,
    "distance": "41 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": true,
    "res-open_time": 16,
    "res-close_time": 4,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/6/21760176/cf1fd421e2afba4e513b82ec4fd40aaf_o2_featured_v2.jpg",
    "names": "Abraj Hotel",
    "rating": "4.3",
    "foodtypes": "Desserts, Bakery",
    "location": "Mysuru",
    "price_for-two": 150,
    "distance": "17 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": true,
    "res-open_time": 14,
    "res-close_time": 2,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/3/22295613/aade5a7026490f1cdc60f7f5dc094f78_featured_v2.jpg?output-format=webp",
    "names": "Green Leaf Cafe",
    "rating": "3.9",
    "foodtypes": "South Indian",
    "location": "Mysuru",
    "price_for-two": 500,
    "distance": "20 min",
    "offer-status":false,

    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 10,
    "res-close_time": 22,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/5/18740985/6e96bfb00b9dd20195385f866d3e0e10_featured_v2.jpg",
    "names": "Blue Lagoon Restaurant",
    "rating": "4.2",
    "foodtypes": "Street Food,Pizza",
    "location": "Kanpur",
    "price_for-two": 2500,
    "distance": "23 min",
    "offer-status":false,

    "offers": "No Offer",
    "alcohol": true,
    "res-open_time": 22,
    "res-close_time": 10,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/2/18741322/e25bd676805b4a01e37b7e13011a18b3_featured_v2.jpg",
    "names": "Skyline Diner",
    "rating": "3.7",
    "foodtypes": "Pizza, Pasta",
    "location": "Tirupati",
    "price_for-two": 2500,
    "distance": "28 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 0,
    "res-close_time": 12,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/6/22032946/e91a99e72302d7e0813b78e4f0978d3a_featured_v2.jpg",
    "names": "Velvet Plate",
    "rating": "4.1",
    "foodtypes": "Biryani",
    "location": "Ahmedabad",
    "price_for-two": 200,
    "distance": "32 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 15,
    "res-close_time": 3,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/chains/6/22179326/8cdbaf4aa2ae34e124b928bb14ccc35e_featured_v2.jpg",
    "names": "Tandoori Nights",
    "rating": "4.7",
    "foodtypes": "Andhra, Telangana",
    "location": "Indore",
    "price_for-two": 200,
    "distance": "16 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 21,
    "res-close_time": 9,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/21066027/cefeafeafbafba5a5fff543a4d6cd86c_featured_v2.jpg",
    "names": "Abraj Hotel",
    "rating": "3.7",
    "foodtypes": "Hyderabadi",
    "location": "Mangaluru",
    "price_for-two": 2500,
    "distance": "21 min",
    "offer-status":true,

    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 14,
    "res-close_time": 2,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/6/22032946/e91a99e72302d7e0813b78e4f0978d3a_featured_v2.jpg",
    "names": "Spice Route Kitchen",
    "rating": "3.6",
    "foodtypes": "South Indian",
    "location": "Kanpur",
    "price_for-two": 150,
    "distance": "42 min",
    "offer-status":true,
    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 3,
    "res-close_time": 15,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/19461655/9079e1636a24751898dba9414c4440ca_featured_v2.jpg",
    "names": "Abraj Hotel",
    "rating": "5.0",
    "foodtypes": "Continental, Turkish, Indian",
    "location": "Kolkata",
    "price_for-two": 2500,
    "distance": "16 min",
    "offer-status":true,
    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 18,
    "res-close_time": 6,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/2/18741322/e25bd676805b4a01e37b7e13011a18b3_featured_v2.jpg",
    "names": "Red Chilli Kitchen",
    "rating": "4.4",
    "foodtypes": "Hyderabadi",
    "location": "Mehdipatnam",
    "price_for-two": 200,
    "distance": "35 min",
    "offers": "No Offer",
    "offer-status":false,
    "alcohol": false,
    "res-open_time": 11,
    "res-close_time": 23,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/21577575/7f35c43ff091a48d6c1acd159af3efb8_featured_v2.jpg",
    "names": "Red Chilli Kitchen",
    "rating": "4.1",
    "foodtypes": "BBQ, Kebabs",
    "location": "Kolkata",
    "price_for-two": 500,
    "distance": "44 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 0,
    "res-close_time": 12,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/20521297/03ba87b3729f88d9fdfd77b50ce6452b_o2_featured_v2.jpg",
    "names": "The Hungry Fork",
    "rating": "3.6",
    "foodtypes": "Biryani",
    "location": "Ahmedabad",
    "price_for-two": 500,
    "distance": "40 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 15,
    "res-close_time": 3,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/2/18741322/e25bd676805b4a01e37b7e13011a18b3_featured_v2.jpg",
    "names": "Ocean Pearl",
    "rating": "3.7",
    "foodtypes": "Andhra, Beverages",
    "location": "Indore",
    "price_for-two": 2500,
    "distance": "34 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 6,
    "res-close_time": 18,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/20983729/7845f3ec74a7d30ed8e6c6463ba6c489_featured_v2.jpg",
    "names": "Babylon Brewery & Club",
    "rating": "4.9",
    "foodtypes": "Maharashtrian,Punjabi",
    "location": "Visakhapatnam",
    "price_for-two": 200,
    "distance": "39 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 17,
    "res-close_time": 5,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/20615641/c1e027ed4473dd688cb237aad8d5b225_featured_v2.jpg",
    "names": "Ajmeer Hotel",
    "rating": "4.8",
    "foodtypes": "North Indian, Biryani",
    "location": "Mumbai",
    "price_for-two": 150,
    "distance": "22 min",
    "offer-status":true,
    "offers": "Flat 50% OFF",
    "alcohol": true,
    "res-open_time": 6,
    "res-close_time": 18,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/8/21819518/fb1aea765438bf1992bf367a05cf9fb8_featured_v2.jpg",
    "names": "Red Chilli Kitchen",
    "rating": "4.0",
    "foodtypes": "Hyderabadi",
    "location": "Ahmedabad",
    "price_for-two": 150,
    "distance": "18 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 13,
    "res-close_time": 1,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/0/18795170/b6047e53bdb9ebce032c9505dc23eed0_featured_v2.jpg",
    "names": "SS Corn Paradise",
    "rating": "3.6",
    "foodtypes": "Andhra, Telangana",
    "location": "Malakpet",
    "price_for-two": 200,
    "distance": "43 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 20,
    "res-close_time": 8,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/21066027/cefeafeafbafba5a5fff543a4d6cd86c_featured_v2.jpg",
    "names": "Hotel Baaratheon",
    "rating": "3.8",
    "foodtypes": "Italian, Mexican",
    "location": "Jaipur",
    "price_for-two": 2500,
    "distance": "20 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 7,
    "res-close_time": 19,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/0/20388020/0fc6b220297879e1f4080d765b7965f0_featured_v2.jpg",
    "names": "Red Chilli Kitchen",
    "rating": "4.9",
    "foodtypes": "Fast Food",
    "location": "Nellore",
    "price_for-two": 200,
    "distance": "21 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 12,
    "res-close_time": 0,
    "pet_friendly": true,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/4/20670174/874629dca183b0e79bcc7dde1c7bb25f_featured_v2.jpg",
    "names": "Maharaj Hotel",
    "rating": "4.3",
    "foodtypes": "Thai, Japanese",
    "location": "Kochi",
    "price_for-two": 200,
    "distance": "32 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 17,
    "res-close_time": 5,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/19150885/0060f85fc89f744b6543c27b6e6db4e2_featured_v2.jpg",
    "names": "Ajmeer Maharaj Hotel",
    "rating": "4.9",
    "foodtypes": "Pizza, Pasta",
    "location": "Himayath Nagar",
    "price_for-two": 150,
    "distance": "34 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 14,
    "res-close_time": 2,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/3/18712173/b78e2f4181db1df2fdd5c5fccb80288f_featured_v2.jpg",
    "names": "Hotel Karthikeya",
    "rating": "4.7",
    "foodtypes": "Burger",
    "location": "Thiruvananthapuram",
    "price_for-two": 200,
    "distance": "28 min",
    "offer-status":true,
    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 3,
    "res-close_time": 15,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/6/22032946/e91a99e72302d7e0813b78e4f0978d3a_featured_v2.jpg",
    "names": "Royal Biryani House",
    "rating": "4.2",
    "foodtypes": "Mughlai",
    "location": "Thiruvananthapuram",
    "price_for-two": 150,
    "distance": "31 min",
    "offer-status":true,
    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 18,
    "res-close_time": 6,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/21503991/cb680d632e34fb3a153ec501c3c6c0ee_featured_v2.jpg",
    "names": "Babylon Brewery & Club",
    "rating": "4.6",
    "foodtypes": "Pizza, Pasta",
    "location": "Thiruvananthapuram",
    "price_for-two": 500,
    "distance": "38 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 18,
    "res-close_time": 6,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/20615641/c1e027ed4473dd688cb237aad8d5b225_featured_v2.jpg",
    "names": "Red Chilli Kitchen",
    "rating": "4.4",
    "foodtypes": "Desserts, Bakery",
    "location": "Amritsar",
    "price_for-two": 2500,
    "distance": "40 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": false,
    "res-open_time": 19,
    "res-close_time": 7,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/5/19461655/9079e1636a24751898dba9414c4440ca_featured_v2.jpg",
    "names": "Peppercorn Restaurant",
    "rating": "3.5",
    "foodtypes": "Street Food,Pizza",
    "location": "Warangal",
    "price_for-two": 200,
    "distance": "44 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 10,
    "res-close_time": 22,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/21066027/cefeafeafbafba5a5fff543a4d6cd86c_featured_v2.jpg",
    "names": "Green Leaf Cafe",
    "rating": "4.4",
    "foodtypes": "Pizza, Pasta",
    "location": "Surat",
    "price_for-two": 150,
    "distance": "32 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 20,
    "res-close_time": 8,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/2/20496432/2a6b302fcf1695f1e84c02a6ea361f70_featured_v2.jpg",
    "names": "Ocean Pearl",
    "rating": "3.7",
    "foodtypes": "Street Food,Pizza",
    "location": "Surat",
    "price_for-two": 500,
    "distance": "21 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": true,
    "res-open_time": 18,
    "res-close_time": 6,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/0/18795170/b6047e53bdb9ebce032c9505dc23eed0_featured_v2.jpg",
    "names": "Mirell Restaurant",
    "rating": "4.5",
    "foodtypes": "Ice Cream, Healthy Food",
    "location": "Nallakunta & Vidyanagar",
    "price_for-two": 150,
    "offer-status":true,
    "distance": "24 min",
    "offers": "Flat 50% OFF",
    "alcohol": true,
    "res-open_time": 0,
    "res-close_time": 12,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/21066027/cefeafeafbafba5a5fff543a4d6cd86c_featured_v2.jpg",
    "names": "Maharaj Hotel",
    "rating": "4.4",
    "foodtypes": "Maharashtrian,Punjabi",
    "location": "Kolkata",
    "price_for-two": 500,
    "distance": "34 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": true,
    "res-open_time": 23,
    "res-close_time": 11,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/20521297/03ba87b3729f88d9fdfd77b50ce6452b_o2_featured_v2.jpg",
    "names": "Harvest Kitchen",
    "rating": "4.1",
    "foodtypes": "North Indian",
    "location": "Madurai",
    "price_for-two": 150,
    "distance": "37 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": true,
    "res-open_time": 20,
    "res-close_time": 8,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/9/21962609/8fb3c84f6912d7fb7e8860c76d58abd5_featured_v2.jpg",
    "names": "Babylon Brewery & Club",
    "rating": "3.8",
    "foodtypes": "Burger",
    "location": "Thiruvananthapuram",
    "price_for-two": 500,
    "distance": "23 min",
    "offer-status":true,
    "offers": "₹101 OFF",
    "alcohol": false,
    "res-open_time": 11,
    "res-close_time": 23,
    "pet_friendly": true,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/21503991/cb680d632e34fb3a153ec501c3c6c0ee_featured_v2.jpg",
    "names": "Abraj Hotel",
    "rating": "4.7",
    "foodtypes": "Maharashtrian,Punjabi",
    "location": "Lucknow",
    "price_for-two": 200,
    "distance": "41 min",
    "offer-status":false,
    "offers": "No Offer",
    "alcohol": false,
    "res-open_time": 10,
    "res-close_time": 22,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/1/22044921/4c9622fe6ba60a5579ca2ef7e1c561c6_o2_featured_v2.jpg?output-format=webp",
    "names": "The Food Factory",
    "rating": "4.7",
    "foodtypes": "Desserts, Bakery",
    "location": "Nallakunta & Vidyanagar",
    "price_for-two": 500,
    "distance": "38 min",
    "offer-status":true,
    "offers": "Flat 10% OFF",
    "alcohol": true,
    "res-open_time": 14,
    "res-close_time": 2,
    "pet_friendly": false,
    "outdoor_seating": true
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/7/20521297/03ba87b3729f88d9fdfd77b50ce6452b_o2_featured_v2.jpg",
    "names": "Mirell Restaurant",
    "rating": "4.7",
    "foodtypes": "Mughlai",
    "location": "Surat",
    "price_for-two": 150,
    "distance": "22 min",
    "offers": "₹101 OFF",
    "offer-status":true,
    "alcohol": false,
    "res-open_time": 8,
    "res-close_time": 20,
    "pet_friendly": false,
    "outdoor_seating": false
  },
  {
    "image": "https://b.zmtcdn.com/data/pictures/3/18712173/b78e2f4181db1df2fdd5c5fccb80288f_featured_v2.jpg",
    "names": "Velvet Plate",
    "rating": "4.2",
    "foodtypes": "Burger",
    "location": "Indore",
    "price_for-two": 2500,
    "distance": "34 min",
    "offer-status":true,
    "offers": "Flat 50% OFF",
    "alcohol": false,
    "res-open_time": 6,
    "res-close_time": 18,
    "pet_friendly": true,
    "outdoor_seating": true
  }
]

       // Wrap EVERYTHING that handles reading parameters and DOM injection inside this listener
window.addEventListener('DOMContentLoaded', () => {
    const urlParams = new URLSearchParams(window.location.search);
    const resId = urlParams.get('id');

    if (resId !== null && restaurants[resId]) {
        const data = restaurants[resId];

        // Core Profile text nodes initializations
        document.getElementById('res-name').innerText = data.names;
        document.getElementById('res-cuisine').innerText = data.foodtypes;
        document.getElementById('res-address').innerText = `${data.location}, India`;
        document.getElementById('menu-title').innerText = `${data.names} Menu`;
        document.getElementById('res-price').innerText = `₹${data["price_for-two"]} for two`;

        // Display values inside the rating widgets
        document.getElementById('res-dining-rating').innerText = `${data.rating} ★`;
        const calculatedDelivery = (parseFloat(data.rating) + 0.1).toFixed(1);
        document.getElementById('res-delivery-rating').innerText = `${calculatedDelivery} ★`;

        // Operational Hours Check
        const currentHour = new Date().getHours();
        let isOpen = false;
        if (data["res-open_time"] < data["res-close_time"]) {
            isOpen = currentHour >= data["res-open_time"] && currentHour < data["res-close_time"];
        } else {
            isOpen = currentHour >= data["res-open_time"] || currentHour < data["res-close_time"];
        }

        const statusEl = document.getElementById('res-status');
        if (statusEl) {
            if (isOpen) {
                statusEl.innerText = "Open Now";
                statusEl.className = "open"; 
                statusEl.style.color = "#24963f";
                statusEl.style.fontWeight = "500";
            } else {
                statusEl.innerText = "Closed";
                statusEl.className = "closed";
                statusEl.style.color = "#e23744";
            }
        }

        // Clean 12-hour AM/PM formatting for hours
        let openHour = data["res-open_time"];
        let suffix = openHour >= 12 ? 'PM' : 'AM';
        openHour = openHour % 12 || 12;
        document.getElementById('res-timing').innerText = `• Opens at ${openHour}:00 ${suffix}`;

        // Inject card image strings into the layout blocks
        document.getElementById('img-main').src = data.image;
        document.getElementById('img-sub1').src = data.image;
        document.getElementById('img-sub2').src = data.image;
        document.getElementById('img-sub3').src = data.image;

        // Context Clustered Links Injections
        document.getElementById('related-title').innerText = `Related to ${data.names}, ${data.location}`;
        document.getElementById('related-tags').innerHTML = `
            <span>Restaurants in ${data.location}</span>, <span>${data.location} Restaurants</span>, 
            <span>${data.location.toLowerCase()} restaurants</span>, <span>Best ${data.location} restaurants</span>, 
            <span>Casual Dining in ${data.location}</span>
        `;

        document.getElementById('around-title').innerText = `Restaurants around ${data.location}`;
        document.getElementById('around-tags').innerHTML = `
            <span>Eateries near ${data.location}</span>, <span>Top food stops around ${data.location}</span>
        `;

        document.getElementById('frequent-tags').innerHTML = `
            <span>${data.names.toLowerCase()} menu</span>, <span>${data.names.toLowerCase()} ${data.location.toLowerCase()} menu</span>, 
            <span>${data.names.toLowerCase()} reviews</span>, <span>${data.names.toLowerCase()} restaurant</span>
        `;

    } else {
        const projectEl = document.querySelector('.project');
        if (projectEl) {
            projectEl.innerHTML = "<div class='container'><h1>Restaurant entry signature not found.</h1><p><a href='newindex.html'>Click here to return to browse index.</a></p></div>";
        }
    }
});